// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type AboutDocumentDataSlicesSlice = never

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  meta_description: prismic.RichTextField

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<AboutDocumentData>,
  'about',
  Lang
>

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Job Title field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField

  /**
   * LinkedIn Url field in *Author*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.linkedin_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_url: prismic.LinkField

  /**
   * Avatar field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<AuthorDocumentData>,
  'author',
  Lang
>

/**
 * Content for Bank documents
 */
interface BankDocumentData {
  /**
   * Name field in *Bank*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bank.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Logo field in *Bank*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bank.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Order field in *Bank*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: bank.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField
}

/**
 * Bank document from Prismic
 *
 * - **API ID**: `bank`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BankDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<BankDocumentData>,
  'bank',
  Lang
>

type BlogPostDocumentDataSlicesSlice = never

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Published Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.published_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_date: prismic.DateField

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Keywords field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField

  /**
   * Introduction Header field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.introduction_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  introduction_header: prismic.KeyTextField

  /**
   * Introduction field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField

  /**
   * Body field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField

  /**
   * Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<'author'>

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<BlogPostDocumentData>,
  'blog_post',
  Lang
>

/**
 * Content for Free Zone documents
 */
interface FreeZoneDocumentData {
  /**
   * Name field in *Free Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_zone.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Logo field in *Free Zone*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: free_zone.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Order field in *Free Zone*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: free_zone.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField

  /**
   * Popular field in *Free Zone*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: free_zone.popular
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  popular: prismic.BooleanField
}

/**
 * Free Zone document from Prismic
 *
 * - **API ID**: `free_zone`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FreeZoneDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<FreeZoneDocumentData>,
  'free_zone',
  Lang
>

/**
 * Content for Quote documents
 */
interface QuoteDocumentData {
  /**
   * Author field in *Quote*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<'author'>

  /**
   * Quote field in *Quote*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField
}

/**
 * Quote document from Prismic
 *
 * - **API ID**: `quote`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuoteDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<QuoteDocumentData>,
  'quote',
  Lang
>

type ServicepageDocumentDataSlicesSlice = Hero1Slice | DescriptionQuoteSlice

/**
 * Content for ServicePage documents
 */
interface ServicepageDocumentData {
  /**
   * Slice Zone field in *ServicePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: servicepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *ServicePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: servicepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *ServicePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: servicepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *ServicePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: servicepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * ServicePage document from Prismic
 *
 * - **API ID**: `servicepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<ServicepageDocumentData>,
  'servicepage',
  Lang
>

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Job Title field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField

  /**
   * Avatar field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>

  /**
   * Description field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Simple 2-3 lines
   * - **API ID Path**: testimonial.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Order field in *Testimonial*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Larger number displayed first
   * - **API ID Path**: testimonial.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField

  /**
   * Profile Link field in *Testimonial*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.profile_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  profile_link: prismic.LinkField
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<TestimonialDocumentData>,
  'testimonial',
  Lang
>

/**
 * Content for Text Page documents
 */
interface TextPageDocumentData {
  /**
   * Title field in *Text Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Body field in *Text Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_page.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField
  /**
   * Meta Title field in *Text Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: text_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Text Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField
}

/**
 * Text Page document from Prismic
 *
 * - **API ID**: `text_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TextPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<TextPageDocumentData>,
  'text_page',
  Lang
>

export type AllDocumentTypes =
  | AboutDocument
  | AuthorDocument
  | BankDocument
  | BlogPostDocument
  | FreeZoneDocument
  | QuoteDocument
  | ServicepageDocument
  | TestimonialDocument
  | TextPageDocument

/**
 * Primary content in *DescriptionQuote → Primary*
 */
export interface DescriptionQuoteSliceDefaultPrimary {
  /**
   * Title field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Quote Author Name field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.quote_author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote_author_name: prismic.KeyTextField

  /**
   * Quote Author Job Title field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.quote_author_job_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote_author_job_title: prismic.KeyTextField

  /**
   * Quote Author Avatar field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.quote_author_avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  quote_author_avatar: prismic.ImageField<never>

  /**
   * Quote Description field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.quote_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote_description: prismic.RichTextField
}

/**
 * Default variation for DescriptionQuote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionQuoteSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<DescriptionQuoteSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *DescriptionQuote*
 */
type DescriptionQuoteSliceVariation = DescriptionQuoteSliceDefault

/**
 * DescriptionQuote Shared Slice
 *
 * - **API ID**: `description_quote`
 * - **Description**: DescriptionQuote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionQuoteSlice = prismic.SharedSlice<
  'description_quote',
  DescriptionQuoteSliceVariation
>

/**
 * Primary content in *Hero1 → Primary*
 */
export interface Hero1SliceDefaultPrimary {
  /**
   * Title Align field in *Hero1 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  align: prismic.SelectField<'Left' | 'Center'>

  /**
   * Title field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Sub Text field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.sub_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_text: prismic.KeyTextField

  /**
   * CTA 1 Text field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.cta_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_1_text: prismic.KeyTextField

  /**
   * CTA 1 Link field in *Hero1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.cta_1_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_1_link: prismic.LinkField

  /**
   * CTA 2 Text field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.cta_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_2_text: prismic.KeyTextField

  /**
   * CTA 2 Link field in *Hero1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.cta_2_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_2_link: prismic.LinkField

  /**
   * Body Image field in *Hero1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.body_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  body_image: prismic.ImageField<never>
}

/**
 * Primary content in *Hero1 → Items*
 */
export interface Hero1SliceDefaultItem {
  /**
   * Bullet Point field in *Hero1 → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.items[].bullet_point
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet_point: prismic.KeyTextField
}

/**
 * Default variation for Hero1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero1SliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<Hero1SliceDefaultPrimary>,
  Simplify<Hero1SliceDefaultItem>
>

/**
 * Slice variation for *Hero1*
 */
type Hero1SliceVariation = Hero1SliceDefault

/**
 * Hero1 Shared Slice
 *
 * - **API ID**: `hero1`
 * - **Description**: Hero1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero1Slice = prismic.SharedSlice<'hero1', Hero1SliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AuthorDocument,
      AuthorDocumentData,
      BankDocument,
      BankDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      FreeZoneDocument,
      FreeZoneDocumentData,
      QuoteDocument,
      QuoteDocumentData,
      ServicepageDocument,
      ServicepageDocumentData,
      ServicepageDocumentDataSlicesSlice,
      TestimonialDocument,
      TestimonialDocumentData,
      TextPageDocument,
      TextPageDocumentData,
      AllDocumentTypes,
      DescriptionQuoteSlice,
      DescriptionQuoteSliceDefaultPrimary,
      DescriptionQuoteSliceVariation,
      DescriptionQuoteSliceDefault,
      Hero1Slice,
      Hero1SliceDefaultPrimary,
      Hero1SliceDefaultItem,
      Hero1SliceVariation,
      Hero1SliceDefault,
    }
  }
}
