// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type AboutDocumentDataSlicesSlice = never

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  meta_description: prismic.RichTextField

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<AboutDocumentData>,
  'about',
  Lang
>

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Job Title field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField

  /**
   * LinkedIn Url field in *Author*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.linkedin_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_url: prismic.LinkField

  /**
   * Avatar field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<AuthorDocumentData>,
  'author',
  Lang
>

/**
 * Content for Bank documents
 */
interface BankDocumentData {
  /**
   * Name field in *Bank*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bank.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Logo field in *Bank*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bank.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Order field in *Bank*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: bank.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField
}

/**
 * Bank document from Prismic
 *
 * - **API ID**: `bank`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BankDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<BankDocumentData>,
  'bank',
  Lang
>

type BlogPostDocumentDataSlicesSlice = never

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Published Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.published_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_date: prismic.DateField

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Keywords field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField

  /**
   * Introduction Header field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.introduction_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  introduction_header: prismic.KeyTextField

  /**
   * Introduction field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField

  /**
   * Body field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField

  /**
   * Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<'author'>

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<BlogPostDocumentData>,
  'blog_post',
  Lang
>

/**
 * Content for Free Zone documents
 */
interface FreeZoneDocumentData {
  /**
   * Name field in *Free Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_zone.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Logo field in *Free Zone*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: free_zone.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Order field in *Free Zone*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: free_zone.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField

  /**
   * Popular field in *Free Zone*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: free_zone.popular
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  popular: prismic.BooleanField
}

/**
 * Free Zone document from Prismic
 *
 * - **API ID**: `free_zone`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FreeZoneDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<FreeZoneDocumentData>,
  'free_zone',
  Lang
>

/**
 * Content for Quote documents
 */
interface QuoteDocumentData {
  /**
   * Author field in *Quote*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<'author'>

  /**
   * Quote field in *Quote*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField
}

/**
 * Quote document from Prismic
 *
 * - **API ID**: `quote`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuoteDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<QuoteDocumentData>,
  'quote',
  Lang
>

type ServicepageDocumentDataSlicesSlice =
  | ContentImageTextSlice
  | ProcessStepsSlice
  | GeneralContentSlice
  | FaqSlice
  | TestimonialsSlice
  | Cta1Slice
  | GridBlocksSlice
  | Hero1Slice
  | DescriptionQuoteSlice

/**
 * Content for ServicePage documents
 */
interface ServicepageDocumentData {
  /**
   * Slice Zone field in *ServicePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: servicepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *ServicePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: servicepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *ServicePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: servicepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *ServicePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: servicepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * ServicePage document from Prismic
 *
 * - **API ID**: `servicepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<ServicepageDocumentData>,
  'servicepage',
  Lang
>

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Job Title field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField

  /**
   * Avatar field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>

  /**
   * Description field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Simple 2-3 lines
   * - **API ID Path**: testimonial.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Order field in *Testimonial*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Larger number displayed first
   * - **API ID Path**: testimonial.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField

  /**
   * Profile Link field in *Testimonial*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.profile_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  profile_link: prismic.LinkField
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<TestimonialDocumentData>,
  'testimonial',
  Lang
>

export type AllDocumentTypes =
  | AboutDocument
  | AuthorDocument
  | BankDocument
  | BlogPostDocument
  | FreeZoneDocument
  | QuoteDocument
  | ServicepageDocument
  | TestimonialDocument

/**
 * Primary content in *ContentImageText → Primary*
 */
export interface ContentImageTextSliceDefaultPrimary {
  /**
   * Title field in *ContentImageText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Sub Text field in *ContentImageText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_text.primary.sub_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_text: prismic.RichTextField

  /**
   * Image field in *ContentImageText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Image Align field in *ContentImageText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_text.primary.image_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_align: prismic.SelectField<'Left' | 'Right'>
}

/**
 * Primary content in *ContentImageText → Items*
 */
export interface ContentImageTextSliceDefaultItem {
  /**
   * Bullet Title field in *ContentImageText → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_text.items[].bullet_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet_title: prismic.KeyTextField

  /**
   * Bullet Text field in *ContentImageText → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_text.items[].bullet_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet_text: prismic.KeyTextField
}

/**
 * Default variation for ContentImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentImageTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContentImageTextSliceDefaultPrimary>,
  Simplify<ContentImageTextSliceDefaultItem>
>

/**
 * Slice variation for *ContentImageText*
 */
type ContentImageTextSliceVariation = ContentImageTextSliceDefault

/**
 * ContentImageText Shared Slice
 *
 * - **API ID**: `content_image_text`
 * - **Description**: ContentImageText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentImageTextSlice = prismic.SharedSlice<
  'content_image_text',
  ContentImageTextSliceVariation
>

/**
 * Primary content in *Cta1 → Primary*
 */
export interface Cta1SliceDefaultPrimary {
  /**
   * Title field in *Cta1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta1.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Sub Text field in *Cta1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta1.primary.sub_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_text: prismic.RichTextField

  /**
   * Bullets field in *Cta1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta1.primary.bullets
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bullets: prismic.RichTextField

  /**
   * CTA Text field in *Cta1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta1.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField

  /**
   * CTA Link field in *Cta1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta1.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField
}

/**
 * Default variation for Cta1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Cta1SliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<Cta1SliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Cta1*
 */
type Cta1SliceVariation = Cta1SliceDefault

/**
 * Cta1 Shared Slice
 *
 * - **API ID**: `cta1`
 * - **Description**: Cta1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Cta1Slice = prismic.SharedSlice<'cta1', Cta1SliceVariation>

/**
 * Primary content in *DescriptionQuote → Primary*
 */
export interface DescriptionQuoteSliceDefaultPrimary {
  /**
   * Title field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Quote Author Name field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.quote_author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote_author_name: prismic.KeyTextField

  /**
   * Quote Author Job Title field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.quote_author_job_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote_author_job_title: prismic.KeyTextField

  /**
   * Quote Author Avatar field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.quote_author_avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  quote_author_avatar: prismic.ImageField<never>

  /**
   * Quote Description field in *DescriptionQuote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_quote.primary.quote_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote_description: prismic.RichTextField
}

/**
 * Default variation for DescriptionQuote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionQuoteSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<DescriptionQuoteSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *DescriptionQuote*
 */
type DescriptionQuoteSliceVariation = DescriptionQuoteSliceDefault

/**
 * DescriptionQuote Shared Slice
 *
 * - **API ID**: `description_quote`
 * - **Description**: DescriptionQuote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionQuoteSlice = prismic.SharedSlice<
  'description_quote',
  DescriptionQuoteSliceVariation
>

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Question field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField

  /**
   * Answer field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<'faq', FaqSliceVariation>

/**
 * Primary content in *GeneralContent → Primary*
 */
export interface GeneralContentSliceDefaultPrimary {
  /**
   * Body field in *GeneralContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_content.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField
}

/**
 * Default variation for GeneralContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GeneralContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GeneralContentSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *GeneralContent*
 */
type GeneralContentSliceVariation = GeneralContentSliceDefault

/**
 * GeneralContent Shared Slice
 *
 * - **API ID**: `general_content`
 * - **Description**: GeneralContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GeneralContentSlice = prismic.SharedSlice<
  'general_content',
  GeneralContentSliceVariation
>

/**
 * Primary content in *GridBlocks → Primary*
 */
export interface GridBlocksSliceDefaultPrimary {
  /**
   * Title field in *GridBlocks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_blocks.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *GridBlocks → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_blocks.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *GridBlocks → Items*
 */
export interface GridBlocksSliceDefaultItem {
  /**
   * Icon field in *GridBlocks → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_blocks.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<'Star' | 'List' | 'Globe' | 'Person' | 'Like' | 'Thought'>

  /**
   * Title field in *GridBlocks → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_blocks.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *GridBlocks → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_blocks.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * CTA Text field in *GridBlocks → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_blocks.items[].cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField

  /**
   * CTA Link field in *GridBlocks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_blocks.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField

  /**
   * Bullets field in *GridBlocks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_blocks.items[].bullets
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bullets: prismic.RichTextField
}

/**
 * Default variation for GridBlocks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridBlocksSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GridBlocksSliceDefaultPrimary>,
  Simplify<GridBlocksSliceDefaultItem>
>

/**
 * Slice variation for *GridBlocks*
 */
type GridBlocksSliceVariation = GridBlocksSliceDefault

/**
 * GridBlocks Shared Slice
 *
 * - **API ID**: `grid_blocks`
 * - **Description**: GridBlocks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridBlocksSlice = prismic.SharedSlice<'grid_blocks', GridBlocksSliceVariation>

/**
 * Primary content in *Hero1 → Primary*
 */
export interface Hero1SliceDefaultPrimary {
  /**
   * Title Align field in *Hero1 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  align: prismic.SelectField<'Left' | 'Center'>

  /**
   * Title field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Sub Text field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.sub_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_text: prismic.KeyTextField

  /**
   * CTA 1 Text field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.cta_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_1_text: prismic.KeyTextField

  /**
   * CTA 1 Link field in *Hero1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.cta_1_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_1_link: prismic.LinkField

  /**
   * CTA 2 Text field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.cta_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_2_text: prismic.KeyTextField

  /**
   * CTA 2 Link field in *Hero1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.cta_2_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_2_link: prismic.LinkField

  /**
   * Body Image field in *Hero1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.body_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  body_image: prismic.ImageField<never>
}

/**
 * Primary content in *Hero1 → Items*
 */
export interface Hero1SliceDefaultItem {
  /**
   * Bullet Point field in *Hero1 → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.items[].bullet_point
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet_point: prismic.KeyTextField
}

/**
 * Default variation for Hero1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero1SliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<Hero1SliceDefaultPrimary>,
  Simplify<Hero1SliceDefaultItem>
>

/**
 * Primary content in *Hero1 → Primary*
 */
export interface Hero1SliceSimplePrimary {
  /**
   * Title field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Sub Text field in *Hero1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.primary.sub_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_text: prismic.KeyTextField
}

/**
 * Simple variation for Hero1 Slice
 *
 * - **API ID**: `simple`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero1SliceSimple = prismic.SharedSliceVariation<
  'simple',
  Simplify<Hero1SliceSimplePrimary>,
  never
>

/**
 * Slice variation for *Hero1*
 */
type Hero1SliceVariation = Hero1SliceDefault | Hero1SliceSimple

/**
 * Hero1 Shared Slice
 *
 * - **API ID**: `hero1`
 * - **Description**: Hero1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero1Slice = prismic.SharedSlice<'hero1', Hero1SliceVariation>

/**
 * Primary content in *ProcessSteps → Primary*
 */
export interface ProcessStepsSliceDefaultPrimary {
  /**
   * Title field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Sub Text field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.sub_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_text: prismic.RichTextField

  /**
   * Step 1 Title field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.step_1_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_1_title: prismic.KeyTextField

  /**
   * Step 1 Text field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.step_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_1_text: prismic.KeyTextField

  /**
   * Step 2 Title field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.step_2_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_2_title: prismic.KeyTextField

  /**
   * Step 2 Text field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.step_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_2_text: prismic.KeyTextField

  /**
   * Step 3 Title field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.step_3_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_3_title: prismic.KeyTextField

  /**
   * Step 3 Text field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.step_3_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_3_text: prismic.KeyTextField
}

/**
 * Default variation for ProcessSteps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessStepsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProcessStepsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ProcessSteps*
 */
type ProcessStepsSliceVariation = ProcessStepsSliceDefault

/**
 * ProcessSteps Shared Slice
 *
 * - **API ID**: `process_steps`
 * - **Description**: ProcessSteps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessStepsSlice = prismic.SharedSlice<'process_steps', ProcessStepsSliceVariation>

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Sub Text field in *Testimonials → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.sub_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_text: prismic.RichTextField

  /**
   * Number to show field in *Testimonials → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Leave unselected to show all
   * - **API ID Path**: testimonials.primary.number_to_show
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  number_to_show: prismic.SelectField<'3' | '6' | '9'>
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<'testimonials', TestimonialsSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AuthorDocument,
      AuthorDocumentData,
      BankDocument,
      BankDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      FreeZoneDocument,
      FreeZoneDocumentData,
      QuoteDocument,
      QuoteDocumentData,
      ServicepageDocument,
      ServicepageDocumentData,
      ServicepageDocumentDataSlicesSlice,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      ContentImageTextSlice,
      ContentImageTextSliceDefaultPrimary,
      ContentImageTextSliceDefaultItem,
      ContentImageTextSliceVariation,
      ContentImageTextSliceDefault,
      Cta1Slice,
      Cta1SliceDefaultPrimary,
      Cta1SliceVariation,
      Cta1SliceDefault,
      DescriptionQuoteSlice,
      DescriptionQuoteSliceDefaultPrimary,
      DescriptionQuoteSliceVariation,
      DescriptionQuoteSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      GeneralContentSlice,
      GeneralContentSliceDefaultPrimary,
      GeneralContentSliceVariation,
      GeneralContentSliceDefault,
      GridBlocksSlice,
      GridBlocksSliceDefaultPrimary,
      GridBlocksSliceDefaultItem,
      GridBlocksSliceVariation,
      GridBlocksSliceDefault,
      Hero1Slice,
      Hero1SliceDefaultPrimary,
      Hero1SliceDefaultItem,
      Hero1SliceSimplePrimary,
      Hero1SliceVariation,
      Hero1SliceDefault,
      Hero1SliceSimple,
      ProcessStepsSlice,
      ProcessStepsSliceDefaultPrimary,
      ProcessStepsSliceVariation,
      ProcessStepsSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    }
  }
}
