// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  blog_feed: dynamic(() => import('./BlogFeed')),
  calendly: dynamic(() => import('./CalendlyHero')),
  content_image_text: dynamic(() => import('./ContentImageText')),
  cta1: dynamic(() => import('./Cta1')),
  description_quote: dynamic(() => import('./DescriptionQuote')),
  faq: dynamic(() => import('./Faq')),
  general_content: dynamic(() => import('./GeneralContent')),
  grid_blocks: dynamic(() => import('./GridBlocks')),
  hero1: dynamic(() => import('./Hero1')),
  process_steps: dynamic(() => import('./ProcessSteps')),
  team: dynamic(() => import('./Team')),
  team_images: dynamic(() => import('./TeamImages')),
  testimonials: dynamic(() => import('./Testimonials')),
  video: dynamic(() => import('./Video')),
}
