// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  blog_section: dynamic(() => import('./BlogSection')),
  cta_enquiry: dynamic(() => import('./CtaEnquiry')),
  description_quote: dynamic(() => import('./DescriptionQuote')),
}
