// This file is generated by Slice Machine. Update with care!

import BlogSection from './BlogSection';
import CtaEnquiry from './CtaEnquiry';

export {
	BlogSection,
	CtaEnquiry,
};

export const components = {
	blog_section: BlogSection,
	cta_enquiry: CtaEnquiry,
};
